GET http://localhost:8080/goods/getOne
Content-Type: application/json

{
  "id": 1
}


###
POST http://localhost:8080/goods/save
Content-Type: application/json

{
  "id": 1,
  "name": "Goods-1",
  "price": 6.66,
  "iconUrl": "iconUrl-1"
}


###